apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o helm
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: namelist-nginx
  name: namelist-nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: namelist-nginx
    spec:
      containers:
      - image: daxnet/namelist-nginx
        name: namelist-nginx
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
