apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o helm
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: namelist-nginx
  name: namelist-nginx
spec:
  ports:
  - name: "8899"
    port: 8899
    targetPort: 80
  selector:
    io.kompose.service: namelist-nginx
status:
  loadBalancer: {}
