apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o helm
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: namelist-service
  name: namelist-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: namelist-service
    spec:
      containers:
      - image: daxnet/namelist-service
        name: namelist-service
        resources: {}
      restartPolicy: Always
status: {}
