apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s.deployment.yaml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-namelist-client
  name: {{ .Release.Name }}-namelist-client
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: {{ .Release.Name }}-namelist-client
status:
  loadBalancer: {}